---
name: Config-Model-CursesUI
version: 1.103
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Curses interface to edit config data through Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.637
  Curses::UI: 0.9606
  Exception::Class: 0
build_requires:
  Log::Log4perl: 0
provides:
  Config::Model::CursesUI:
    file: lib/Config/Model/CursesUI.pm
    version: 1.103
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
