---
name: Config-Model-CursesUI
version: 1.005
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Curses interface for Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.614
  Curses::UI: 0.95
  Exception::Class: 0
  Log::Log4perl: 0
provides:
  Config::Model::CursesUI:
    file: lib/Config/Model/CursesUI.pm
    version: 1.005
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
