---
name: Config-Model-CursesUI
version: 1.102
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Curses interface to edit config data through Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.633
  Curses::UI: 0.9606
  Exception::Class: 0
provides:
  Config::Model::CursesUI:
    file: lib/Config/Model/CursesUI.pm
    version: 1.102
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
